[package]
name = "lemoncraft-common-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
simd = ["vek/platform_intrinsics"]

default = ["simd"]

[dependencies]
common = { package = "lemoncraft-common", path = ".." }
common-net = { package = "lemoncraft-common-net", path = "../net" }
common-ecs = { package = "lemoncraft-common-ecs", path = "../ecs" }
common-base = { package = "lemoncraft-common-base", path = "../base" }
common-assets = { package = "lemoncraft-common-assets", path = "../assets", optional = true}

rayon = { workspace = true }
num_cpus = "1.0"
tracing = { workspace = true }
vek = { workspace = true }

# Data structures
hashbrown = { workspace = true }

# ECS
specs = { workspace = true, features = ["serde", "storage-event-control", "derive"] }

scopeguard = "1.1.0"
timer-queue = "0.1.0"
async-trait = { workspace = true }
futures = "0.3.30"
thread-priority = { workspace = true }

# Tweak running code
#inline_tweak = { version = "1.0.8", features = ["release_tweak"] }
